CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE TABLE "Measures" (
        "Id" integer NOT NULL,
        "Name" character varying(5) NOT NULL,
        CONSTRAINT "PK_Measures" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE TABLE "ProductStatuses" (
        "Id" integer NOT NULL,
        "Name" character varying(20) NOT NULL,
        CONSTRAINT "PK_ProductStatuses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE TABLE "Shops" (
        "Id" integer NOT NULL,
        "Name" character varying(20) NOT NULL,
        CONSTRAINT "PK_Shops" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(255) NOT NULL,
        "PasswordHash" character varying(64) NOT NULL,
        "Name" character varying(50) NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE TABLE "Products" (
        "ShopId" integer NOT NULL,
        "Name" text NOT NULL,
        "Price" numeric(14,2) NOT NULL,
        "FullLinkProduct" character varying(100) NOT NULL,
        "FullLinkImage" character varying(100) NOT NULL,
        "MeasureId" integer NOT NULL,
        "ProductStatusId" integer NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Name", "ShopId"),
        CONSTRAINT "FK_Products_Measures_MeasureId" FOREIGN KEY ("MeasureId") REFERENCES "Measures" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Products_ProductStatuses_ProductStatusId" FOREIGN KEY ("ProductStatusId") REFERENCES "ProductStatuses" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Products_Shops_ShopId" FOREIGN KEY ("ShopId") REFERENCES "Shops" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE TABLE "Requests" (
        "UserId" integer NOT NULL,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Requests" PRIMARY KEY ("UserId", "Name"),
        CONSTRAINT "FK_Requests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    INSERT INTO "Measures" ("Id", "Name")
    VALUES (0, 'Kg');
    INSERT INTO "Measures" ("Id", "Name")
    VALUES (1, 'L');
    INSERT INTO "Measures" ("Id", "Name")
    VALUES (2, 'No');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    INSERT INTO "ProductStatuses" ("Id", "Name")
    VALUES (0, 'Updated');
    INSERT INTO "ProductStatuses" ("Id", "Name")
    VALUES (1, 'NeedRemoval');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    INSERT INTO "Shops" ("Id", "Name")
    VALUES (0, 'Silpo');
    INSERT INTO "Shops" ("Id", "Name")
    VALUES (1, 'Fozzy');
    INSERT INTO "Shops" ("Id", "Name")
    VALUES (2, 'Fora');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE INDEX "IX_Products_MeasureId" ON "Products" ("MeasureId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE INDEX "IX_Products_ProductStatusId" ON "Products" ("ProductStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    CREATE INDEX "IX_Products_ShopId" ON "Products" ("ShopId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241211213359_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241211213359_InitialCreate', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    ALTER TABLE "Products" RENAME COLUMN "Price" TO "PriceUnified";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    ALTER TABLE "Products" ALTER COLUMN "FullLinkProduct" TYPE character varying(2048);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    ALTER TABLE "Products" ALTER COLUMN "FullLinkImage" TYPE character varying(2048);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    ALTER TABLE "Products" ALTER COLUMN "Name" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    ALTER TABLE "Products" ADD "PriceInitial" numeric(14,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    UPDATE "Measures" SET "Name" = 'M'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    INSERT INTO "Measures" ("Id", "Name")
    VALUES (3, 'No');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    INSERT INTO "Users" ("Id", "Email", "Name", "PasswordHash")
    VALUES (-1, 'admin@gmail.com', 'admin', 'admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    INSERT INTO "Requests" ("Name", "UserId")
    VALUES ('м''ясо', -1);
    INSERT INTO "Requests" ("Name", "UserId")
    VALUES ('овочі', -1);
    INSERT INTO "Requests" ("Name", "UserId")
    VALUES ('хліб', -1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Users"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Users") + 1,
            nextval(pg_get_serial_sequence('"Users"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241212181459_AdditionalInfoAboutProducts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241212181459_AdditionalInfoAboutProducts', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215205326_IncreasePasswordHashSize') THEN
    ALTER TABLE "Users" ALTER COLUMN "PasswordHash" TYPE character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241215205326_IncreasePasswordHashSize') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241215205326_IncreasePasswordHashSize', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    ALTER TABLE "Requests" ADD "SortId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    ALTER TABLE "Requests" ADD "SortOrderId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    CREATE TABLE "Sort" (
        "Id" integer NOT NULL,
        "Name" character varying(30) NOT NULL,
        CONSTRAINT "PK_Sort" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    CREATE TABLE "SortOrder" (
        "Id" integer NOT NULL,
        "Name" character varying(5) NOT NULL,
        CONSTRAINT "PK_SortOrder" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    UPDATE "Requests" SET "SortId" = 0, "SortOrderId" = 0
    WHERE "Name" = 'м''ясо' AND "UserId" = -1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    UPDATE "Requests" SET "SortId" = 0, "SortOrderId" = 0
    WHERE "Name" = 'овочі' AND "UserId" = -1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    UPDATE "Requests" SET "SortId" = 0, "SortOrderId" = 0
    WHERE "Name" = 'хліб' AND "UserId" = -1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    INSERT INTO "Sort" ("Id", "Name")
    VALUES (0, 'Name');
    INSERT INTO "Sort" ("Id", "Name")
    VALUES (1, 'UnifiedPrice');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    INSERT INTO "SortOrder" ("Id", "Name")
    VALUES (0, 'Asc');
    INSERT INTO "SortOrder" ("Id", "Name")
    VALUES (1, 'Desc');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    CREATE INDEX "IX_Requests_SortId" ON "Requests" ("SortId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    CREATE INDEX "IX_Requests_SortOrderId" ON "Requests" ("SortOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    ALTER TABLE "Requests" ADD CONSTRAINT "FK_Requests_SortOrder_SortOrderId" FOREIGN KEY ("SortOrderId") REFERENCES "SortOrder" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    ALTER TABLE "Requests" ADD CONSTRAINT "FK_Requests_Sort_SortId" FOREIGN KEY ("SortId") REFERENCES "Sort" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241216164846_AddSortParametersToRequest') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241216164846_AddSortParametersToRequest', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217164048_SortByPrice') THEN
    INSERT INTO "Sort" ("Id", "Name")
    VALUES (2, 'Price');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217164048_SortByPrice') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241217164048_SortByPrice', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217175559_ExtendedQueryList') THEN
    DELETE FROM "Requests"
    WHERE "Name" = 'овочі' AND "UserId" = -1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217175559_ExtendedQueryList') THEN
    ALTER TABLE "Products" ALTER COLUMN "Name" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217175559_ExtendedQueryList') THEN
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('вода', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('зубна паста', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('йогурт', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('кава зерно', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('кава розчинна', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('ковбаса', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('консерви', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('корм', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('крупа', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('макаронні вироби', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('мило', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('молоко', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('морозиво', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('напій', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('овоч', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('олія', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('оцет', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('печиво', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('підгузки', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('пральний порошок', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('риба', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('сардельки', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('сир', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('сік', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('сіль', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('сосиски', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('соус', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('спеції', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('торт', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('туалетний папір', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('фрукт', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('цукор', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('чай', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('шампунь', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('шоколад', -1, 0, 0);
    INSERT INTO "Requests" ("Name", "UserId", "SortId", "SortOrderId")
    VALUES ('яйця', -1, 0, 0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217175559_ExtendedQueryList') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241217175559_ExtendedQueryList', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217192810_ChangePKOfProductToFullProductLink') THEN
    ALTER TABLE "Products" DROP CONSTRAINT "PK_Products";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217192810_ChangePKOfProductToFullProductLink') THEN
    ALTER TABLE "Products" ADD CONSTRAINT "PK_Products" PRIMARY KEY ("FullLinkProduct");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241217192810_ChangePKOfProductToFullProductLink') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241217192810_ChangePKOfProductToFullProductLink', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241219162318_SmallFixes') THEN
    ALTER TABLE "Requests" ALTER COLUMN "Name" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241219162318_SmallFixes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241219162318_SmallFixes', '9.0.0');
    END IF;
END $EF$;
COMMIT;


